// user:{
// 	softskill:{
// 		painting:{
// 			starpoints:0,
// 			level:"Beginner",
// 			Beginner:{
// 				fillcolor:["","","","",""]
// 			},
// 			Intermidiate:{
// 				fillcolor:[color1[0],color1[1],color2[0],color2[1],color3[0],color3[1],color4[0],color4[1],color5[0],color5[1]]
// 			},
// 			Advanced:{
// 				fillcolor:[	color1[0],
// 						color1[1],
// 						color1[2],
// 						color2[0],
// 						color2[1],
// 						color2[2],
// 						color3[0],
// 						color3[1],
// 						color3[2],
// 						color4[0],
// 						color4[1],
// 						color4[2],
// 						color5[0],
// 						color5[1],
// 						color5[2]]
// 			},
// 		}
		
// 	},
// 	learningskill:{}
// }